name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: Test with Python ${{ matrix.version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade --no-cache-dir -e ".[dev]"

      - name: Run tests
        run: |
            make test
